-- Autogenerated by Luapress v3.4
-- For available configuation options, see: fizzadar.com/luapress
-- Or see the default config at:
-- github.com/Fizzadar/Luapress/blob/develop/luapress/default_config.lua

local config = {
    url = '',
    title = 'Sol Documentation',
    link_dirs = false,
    index_page = 'home',
    force_index_page = true,
}

return config
